# Site settings
title: Dev. Fallingstar - Who Am I?
description: Who the heck is Dev Fallingstar
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dev. Fallingstar
user_description: Swift를 이용해서 iOS 어플리케이션을, Java를 이용해서 안드로이드 어플리케이션을 제작합니다. 언제까지나 Frontend에 머무를 수 없기에 Backend를 다루기 위해 Python과 Flask을 통해서 REST API 서버를 개발합니다. 또, 언제까지나 개발자로 머무를 수 없기에 연구자가 되기 위해 VR 스트리밍을 활용한 네트워크 시스템을 연구하고 있습니다.
user_title: Software Developer
email: stardung86@gmail.com
twitter_username: devFallingstar
github_username:  devFallingstar
gplus_username:  양유성

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
